
package vsp3.hawmetering;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HAWMeteringWebserviceService", targetNamespace = "http://hawmetering/", wsdlLocation = "http://localhost:9999/hawmetering/nw?wsdl")
public class HAWMeteringWebserviceService
    extends Service
{

    private final static URL HAWMETERINGWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(vsp3.hawmetering.HAWMeteringWebserviceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = vsp3.hawmetering.HAWMeteringWebserviceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/hawmetering/nw?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/hawmetering/nw?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HAWMETERINGWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public HAWMeteringWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HAWMeteringWebserviceService() {
        super(HAWMETERINGWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://hawmetering/", "HAWMeteringWebserviceService"));
    }

    /**
     * 
     * @return
     *     returns HAWMeteringWebservice
     */
    @WebEndpoint(name = "HAWMeteringWebservicePort")
    public HAWMeteringWebservice getHAWMeteringWebservicePort() {
        return super.getPort(new QName("http://hawmetering/", "HAWMeteringWebservicePort"), HAWMeteringWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HAWMeteringWebservice
     */
    @WebEndpoint(name = "HAWMeteringWebservicePort")
    public HAWMeteringWebservice getHAWMeteringWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hawmetering/", "HAWMeteringWebservicePort"), HAWMeteringWebservice.class, features);
    }

}
