
package server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "server_service", targetNamespace = "http://server/", wsdlLocation = "file:/C:/Users/Fettlaus/workspacejava/WebServices/Testprojekt/src/server.wsdl")
public class ServerService
    extends Service
{

    private final static URL SERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(server.ServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = server.ServerService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Fettlaus/workspacejava/WebServices/Testprojekt/src/server.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Fettlaus/workspacejava/WebServices/Testprojekt/src/server.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVERSERVICE_WSDL_LOCATION = url;
    }

    public ServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerService() {
        super(SERVERSERVICE_WSDL_LOCATION, new QName("http://server/", "server_service"));
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "serverSOAP")
    public Server getServerSOAP() {
        return super.getPort(new QName("http://server/", "serverSOAP"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "serverSOAP")
    public Server getServerSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "serverSOAP"), Server.class, features);
    }

}
