
package sensor;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SensorService", targetNamespace = "http://sensor/", wsdlLocation = "file:/C:/Users/Fettlaus/workspacejava/WebServices/Messwerterfassung/src/Sensor.wsdl")
public class SensorService
    extends Service
{

    private final static URL SENSORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sensor.SensorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sensor.SensorService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Fettlaus/workspacejava/WebServices/Messwerterfassung/src/Sensor.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Fettlaus/workspacejava/WebServices/Messwerterfassung/src/Sensor.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SENSORSERVICE_WSDL_LOCATION = url;
    }

    public SensorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SensorService() {
        super(SENSORSERVICE_WSDL_LOCATION, new QName("http://sensor/", "SensorService"));
    }

    /**
     * 
     * @return
     *     returns Sensor
     */
    @WebEndpoint(name = "SensorSOAP")
    public Sensor getSensorSOAP() {
        return super.getPort(new QName("http://sensor/", "SensorSOAP"), Sensor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Sensor
     */
    @WebEndpoint(name = "SensorSOAP")
    public Sensor getSensorSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://sensor/", "SensorSOAP"), Sensor.class, features);
    }

}
