
package sensor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Sensor", targetNamespace = "http://sensor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sensor {


    /**
     * 
     * @return
     *     returns sensor.SensorList
     */
    @WebMethod(action = "http://sensor/getSensorList")
    @WebResult(name = "list", partName = "list")
    public SensorList getSensorList();

    /**
     * 
     * @param requestingID
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://sensor/election")
    @WebResult(name = "success", partName = "success")
    public boolean election(
        @WebParam(name = "requestingID", partName = "requestingID")
        long requestingID);

    /**
     * 
     * @param sensor
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://sensor/addSensor")
    @WebResult(name = "success", partName = "success")
    public boolean addSensor(
        @WebParam(name = "sensor", partName = "sensor")
        SensorObj sensor);

    /**
     * 
     * @param coordinator
     */
    @WebMethod(action = "http://sensor/setCoordinator")
    public void setCoordinator(
        @WebParam(name = "coordinator", partName = "coordinator")
        SensorObj coordinator);

}
