
package sensor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Sensor", targetNamespace = "http://sensor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sensor {


    /**
     * 
     * @param setSensorListRequest
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://sensor/setSensorList")
    @WebResult(name = "setSensorListResponse", partName = "setSensorListResponse")
    public boolean setSensorList(
        @WebParam(name = "setSensorListRequest", partName = "setSensorListRequest")
        SensorList setSensorListRequest);

}
