
package sensor;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SensorRef", targetNamespace = "http://sensor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SensorRef {


    /**
     * 
     */
    @WebMethod
    public void getsomething();

}
